variable "rg_name" {}
variable "rg_location" {}
variable "web_username" {}
variable "web_host_name" {}
variable "web_pass" {}
variable "web_vm_name" {}
variable "web_subnet_id" {}
variable "app_subnet_id" {}
variable "db_subnet_id" {}